[tool.black]
target-version = ["py36", "py37", "py38", "py310"]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 79
ignore = []
exclude = [
    ".git",
    "__pycache__",
    "venv",
]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
skip = ".venv,venv,env"
src_paths = ["src"]

[tool.mypy]
python_version = '3.10'
plugins = []
mypy_path = 'src'
exclude = []
follow_imports = 'silent'
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true

[[tool.mypy.overrides]]
module = ["twilio.rest"]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings"
